In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('../Data/NYCTaxiFares.csv')

In [3]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0        40.730521         -73.975499         40.744746                1  
1        40.740558         -73.974232         40.744114                1  
2        40.751118         -73.960064         40.766235                2  
3        40.756422         -73.971205         40.748192                1  
4        40.734202         -73.905956         40.743115                1

In [4]:
df.describe()

fare_amount     fare_class  pickup_longitude  pickup_latitude  \
count  120000.000000  120000.000000     120000.000000    120000.000000   
mean       10.040326       0.333333        -73.976626        40.751443   
std         7.500134       0.471406          0.031497         0.025821   
min         2.500000       0.000000        -74.465447        40.121653   
25%         5.700000       0.000000        -73.992386        40.736594   
50%         7.700000       0.000000        -73.982084        40.753661   
75%        11.300000       1.000000        -73.968710        40.768020   
max        49.900000       1.000000        -73.311845        40.981292   

       dropoff_longitude  dropoff_latitude  passenger_count  
count      120000.000000     120000.000000    120000.000000  
mean          -73.974501         40.751695         1.347167  
std             0.032419          0.030279         0.759263  
min           -74.443323         40.164927         1.000000  
25%           -73.991478         40.735914         1.000000  
50%           -73.980411         40.754441         1.000000  
75%           -73.965500         40.768880         1.000000  
max           -73.496140         40.993498         5.000000

In [5]:
def haversine_distance(df, lat1, long1, lat2, long2):
    """
    Calculates the haversine distance between 2 sets of GPS coordinates in df
    """
    r = 6371  # average radius of Earth in kilometers
       
    phi1 = np.radians(df[lat1])
    phi2 = np.radians(df[lat2])
    
    delta_phi = np.radians(df[lat2]-df[lat1])
    delta_lambda = np.radians(df[long2]-df[long1])
     
    a = np.sin(delta_phi/2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    d = (r * c) # in kilometers

    return d

### Feature engineering

In [6]:
df['dist_km'] = haversine_distance(df, 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude')

In [7]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km  
0  1.925522  
1  1.765370  
2  3.818373  
3  2.158661  
4  9.457764

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   pickup_datetime    120000 non-null  object 
 1   fare_amount        120000 non-null  float64
 2   fare_class         120000 non-null  int64  
 3   pickup_longitude   120000 non-null  float64
 4   pickup_latitude    120000 non-null  float64
 5   dropoff_longitude  120000 non-null  float64
 6   dropoff_latitude   120000 non-null  float64
 7   passenger_count    120000 non-null  int64  
 8   dist_km            120000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 8.2+ MB


In [9]:
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype              
---  ------             --------------   -----              
 0   pickup_datetime    120000 non-null  datetime64[ns, UTC]
 1   fare_amount        120000 non-null  float64            
 2   fare_class         120000 non-null  int64              
 3   pickup_longitude   120000 non-null  float64            
 4   pickup_latitude    120000 non-null  float64            
 5   dropoff_longitude  120000 non-null  float64            
 6   dropoff_latitude   120000 non-null  float64            
 7   passenger_count    120000 non-null  int64              
 8   dist_km            120000 non-null  float64            
dtypes: datetime64[ns, UTC](1), float64(6), int64(2)
memory usage: 8.2 MB


In [11]:
my_time = df['pickup_datetime'][0]

In [12]:
df['EDTdate'] = df['pickup_datetime'] - pd.Timedelta(hours=4)

In [13]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km                   EDTdate  
0  1.925522 2010-04-19 04:17:56+00:00  
1  1.765370 2010-04-17 11:43:53+00:00  
2  3.818373 2010-04-17 07:23:26+00:00  
3  2.158661 2010-04-11 17:25:03+00:00  
4  9.457764 2010-04-16 22:19:01+00:00

In [15]:
df['Hour'] = df['EDTdate'].dt.hour

In [19]:
df['MORorAFTorNIG'] = df['Hour'].apply(lambda x: 'mor' if x<12 else 'aft' if x< 18 else 'nig')

In [16]:
df['AMorPM'] = np.where(df['Hour'] < 12, 'am', 'pm')

In [22]:
df['Weekday'] = df['EDTdate'].dt.strftime('%a')

In [23]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km                   EDTdate  Hour AMorPM MORorAFTorNIG Weekday  
0  1.925522 2010-04-19 04:17:56+00:00     4     am           mor     Mon  
1  1.765370 2010-04-17 11:43:53+00:00    11     am           mor     Sat  
2  3.818373 2010-04-17 07:23:26+00:00     7     am           mor     Sat  
3  2.158661 2010-04-11 17:25:03+00:00    17     pm           aft     Sun  
4  9.457764 2010-04-16 22:19:01+00:00    22     pm           nig     Fri

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype              
---  ------             --------------   -----              
 0   pickup_datetime    120000 non-null  datetime64[ns, UTC]
 1   fare_amount        120000 non-null  float64            
 2   fare_class         120000 non-null  int64              
 3   pickup_longitude   120000 non-null  float64            
 4   pickup_latitude    120000 non-null  float64            
 5   dropoff_longitude  120000 non-null  float64            
 6   dropoff_latitude   120000 non-null  float64            
 7   passenger_count    120000 non-null  int64              
 8   dist_km            120000 non-null  float64            
 9   EDTdate            120000 non-null  datetime64[ns, UTC]
 10  Hour               120000 non-null  int32              
 11  AMorPM             120000 non-null  object             
 12  MORorAFTorNIG      120000 non-

In [25]:
df.columns

Index(['pickup_datetime', 'fare_amount', 'fare_class', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count', 'dist_km', 'EDTdate', 'Hour', 'AMorPM',
       'MORorAFTorNIG', 'Weekday'],
      dtype='object')

In [27]:
categorical_cols = ['Hour', 'AMorPM', 'MORorAFTorNIG', 'Weekday']
Numercial_cols = ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'passenger_count', 'dist_km']

In [28]:
y_col = ['fare_amount']

In [30]:
for cat in categorical_cols:
    df[cat] = df[cat].astype('category')

In [31]:
df.dtypes

pickup_datetime      datetime64[ns, UTC]
fare_amount                      float64
fare_class                         int64
pickup_longitude                 float64
pickup_latitude                  float64
dropoff_longitude                float64
dropoff_latitude                 float64
passenger_count                    int64
dist_km                          float64
EDTdate              datetime64[ns, UTC]
Hour                            category
AMorPM                          category
MORorAFTorNIG                   category
Weekday                         category
dtype: object

In [32]:
df['Hour'].head()

0     4
1    11
2     7
3    17
4    22
Name: Hour, dtype: category
Categories (24, int32): [0, 1, 2, 3, ..., 20, 21, 22, 23]

In [33]:
df['AMorPM'].head()

0    am
1    am
2    am
3    pm
4    pm
Name: AMorPM, dtype: category
Categories (2, object): ['am', 'pm']

In [34]:
df['MORorAFTorNIG'].head()

0    mor
1    mor
2    mor
3    aft
4    nig
Name: MORorAFTorNIG, dtype: category
Categories (3, object): ['aft', 'mor', 'nig']

In [35]:
df['Weekday'].head()

0    Mon
1    Sat
2    Sat
3    Sun
4    Fri
Name: Weekday, dtype: category
Categories (7, object): ['Fri', 'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Wed']

In [39]:
df['MORorAFTorNIG'].cat.codes.values

array([1, 1, 1, ..., 0, 1, 0], dtype=int8)

In [40]:
hr = df['Hour'].cat.codes.values
ampm = df['AMorPM'].cat.codes.values
moraftnig = df['MORorAFTorNIG'].cat.codes.values
weekday = df['Weekday'].cat.codes.values

In [41]:
cats = np.stack([hr, ampm, moraftnig, weekday], axis=1)

In [42]:
cats

array([[ 4,  0,  1,  1],
       [11,  0,  1,  2],
       [ 7,  0,  1,  2],
       ...,
       [14,  1,  0,  3],
       [ 4,  0,  1,  5],
       [12,  1,  0,  2]], dtype=int8)

### NOTE: This can be done in one line of code using a list comprehension:
cats = np.stack([df[col].cat.codes.values for col incategorical_colss], 1)

In [44]:
# convert np.array to tensors

cats = torch.tensor(cats, dtype=torch.int64)

In [45]:
nums = np.stack([df[col].values for col in Numercial_cols], axis=1)

In [48]:
nums = torch.tensor(nums, dtype=torch.float)

In [49]:
nums

tensor([[-73.9924,  40.7305, -73.9755,  40.7447,   1.0000,   1.9255],
        [-73.9901,  40.7406, -73.9742,  40.7441,   1.0000,   1.7654],
        [-73.9941,  40.7511, -73.9601,  40.7662,   2.0000,   3.8184],
        ...,
        [-73.9886,  40.7498, -74.0115,  40.7078,   3.0000,   2.8595],
        [-74.0044,  40.7245, -73.9927,  40.7308,   1.0000,   1.3207],
        [-73.9554,  40.7719, -73.9676,  40.7630,   3.0000,   1.3848]])

In [52]:
y = torch.tensor(df[y_col].values, dtype=torch.float)

In [53]:
nums.shape

torch.Size([120000, 6])

In [54]:
cats.shape

torch.Size([120000, 4])

In [55]:
y.shape

torch.Size([120000, 1])

In [ ]:
cat_szs = [len(